//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_TUT_Adopt_Me_v3.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_header> item_header { get; set; }
        public virtual DbSet<pet> pets { get; set; }
        public virtual DbSet<pet_header> pet_header { get; set; }
        public virtual DbSet<shop> shops { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<wish_list> wish_list { get; set; }
        public virtual DbSet<wishlist> wishlists { get; set; }
    }
}
