//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE_TUT_Adopt_Me_v3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pet()
        {
            this.wishlists = new HashSet<wishlist>();
            this.pet_header = new HashSet<pet_header>();
        }
    
        public string pet_id { get; set; }
        public string shop_id { get; set; }
        public string pet_name { get; set; }
        public int umur { get; set; }
        public int price { get; set; }
        public string gender { get; set; }
        public string species { get; set; }
        public string pet_image_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pet_header> pet_header { get; set; }
        public virtual shop shop { get; set; }
    }
}
